//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 27/02/2025 13:45:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Extensions.Configuration;

namespace BddtournoiContext
{

    [DatabaseAttribute(Name = "bddtournois")]
    [ProviderAttribute(typeof(Devart.Data.MySql.Linq.Provider.MySqlDataProvider))]
    public partial class BddtournoiDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(BddtournoiDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertGestionnairesappli(Gestionnairesappli instance);
        partial void UpdateGestionnairesappli(Gestionnairesappli instance);
        partial void DeleteGestionnairesappli(Gestionnairesappli instance);
        partial void InsertParticipant(Participant instance);
        partial void UpdateParticipant(Participant instance);
        partial void DeleteParticipant(Participant instance);
        partial void InsertSport(Sport instance);
        partial void UpdateSport(Sport instance);
        partial void DeleteSport(Sport instance);
        partial void InsertTournoi(Tournoi instance);
        partial void UpdateTournoi(Tournoi instance);
        partial void DeleteTournoi(Tournoi instance);

        #endregion

        public BddtournoiDataContext() :
        base(GetConnectionString("BddtournoiDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public BddtournoiDataContext(MappingSource mappingSource) :
        base(GetConnectionString("BddtournoiDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        public BddtournoiDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public BddtournoiDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public BddtournoiDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public BddtournoiDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Gestionnairesappli> Gestionnairesapplis
        {
            get
            {
                return this.GetTable<Gestionnairesappli>();
            }
        }

        public Devart.Data.Linq.Table<Participant> Participants
        {
            get
            {
                return this.GetTable<Participant>();
            }
        }

        public Devart.Data.Linq.Table<Sport> Sports
        {
            get
            {
                return this.GetTable<Sport>();
            }
        }

        public Devart.Data.Linq.Table<Tournoi> Tournois
        {
            get
            {
                return this.GetTable<Tournoi>();
            }
        }
    }
}

namespace BddtournoiContext
{

    /// <summary>
    /// There are no comments for BddtournoiContext.Gestionnairesappli in the schema.
    /// </summary>
    [Table(Name = @"bddtournois.gestionnairesappli")]
    public partial class Gestionnairesappli : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _IdGestionnaire;

        private string _Login;

        private string _MotDpass;
        #pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdGestionnaireChanging(int value);
        partial void OnIdGestionnaireChanged();
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        partial void OnMotDpassChanging(string value);
        partial void OnMotDpassChanged();
        #endregion

        public Gestionnairesappli()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdGestionnaire in the schema.
        /// </summary>
        [Column(Name = @"idGestionnaire", Storage = "_IdGestionnaire", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int IdGestionnaire
        {
            get
            {
                return this._IdGestionnaire;
            }
            set
            {
                if (this._IdGestionnaire != value)
                {
                    this.OnIdGestionnaireChanging(value);
                    this.SendPropertyChanging("IdGestionnaire");
                    this._IdGestionnaire = value;
                    this.SendPropertyChanged("IdGestionnaire");
                    this.OnIdGestionnaireChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Login in the schema.
        /// </summary>
        [Column(Name = @"login", Storage = "_Login", CanBeNull = false, DbType = "TEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                if (this._Login != value)
                {
                    this.OnLoginChanging(value);
                    this.SendPropertyChanging("Login");
                    this._Login = value;
                    this.SendPropertyChanged("Login");
                    this.OnLoginChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MotDpass in the schema.
        /// </summary>
        [Column(Name = @"motDpass", Storage = "_MotDpass", CanBeNull = false, DbType = "TEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MotDpass
        {
            get
            {
                return this._MotDpass;
            }
            set
            {
                if (this._MotDpass != value)
                {
                    this.OnMotDpassChanging(value);
                    this.SendPropertyChanging("MotDpass");
                    this._MotDpass = value;
                    this.SendPropertyChanged("MotDpass");
                    this.OnMotDpassChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for BddtournoiContext.Participant in the schema.
    /// </summary>
    [Table(Name = @"bddtournois.participant")]
    public partial class Participant : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Prenom;

        private string _Nom;

        private System.DateTime _DateNaissance;

        private string _Sexe;

        private byte[] _Photo;

        private int _Tournoi;
        #pragma warning restore 0649

        private EntityRef<Tournoi> _Tournoi1;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnPrenomChanging(string value);
        partial void OnPrenomChanged();
        partial void OnNomChanging(string value);
        partial void OnNomChanged();
        partial void OnDateNaissanceChanging(System.DateTime value);
        partial void OnDateNaissanceChanged();
        partial void OnSexeChanging(string value);
        partial void OnSexeChanged();
        partial void OnPhotoChanging(byte[] value);
        partial void OnPhotoChanged();
        partial void OnTournoiChanging(int value);
        partial void OnTournoiChanged();
        #endregion

        public Participant()
        {
            this._Tournoi1  = default(EntityRef<Tournoi>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Prenom in the schema.
        /// </summary>
        [Column(Name = @"prenom", Storage = "_Prenom", CanBeNull = false, DbType = "TEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Prenom
        {
            get
            {
                return this._Prenom;
            }
            set
            {
                if (this._Prenom != value)
                {
                    this.OnPrenomChanging(value);
                    this.SendPropertyChanging("Prenom");
                    this._Prenom = value;
                    this.SendPropertyChanged("Prenom");
                    this.OnPrenomChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Nom in the schema.
        /// </summary>
        [Column(Name = @"nom", Storage = "_Nom", CanBeNull = false, DbType = "TEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Nom
        {
            get
            {
                return this._Nom;
            }
            set
            {
                if (this._Nom != value)
                {
                    this.OnNomChanging(value);
                    this.SendPropertyChanging("Nom");
                    this._Nom = value;
                    this.SendPropertyChanged("Nom");
                    this.OnNomChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateNaissance in the schema.
        /// </summary>
        [Column(Name = @"dateNaissance", Storage = "_DateNaissance", CanBeNull = false, DbType = "DATE NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime DateNaissance
        {
            get
            {
                return this._DateNaissance;
            }
            set
            {
                if (this._DateNaissance != value)
                {
                    this.OnDateNaissanceChanging(value);
                    this.SendPropertyChanging("DateNaissance");
                    this._DateNaissance = value;
                    this.SendPropertyChanged("DateNaissance");
                    this.OnDateNaissanceChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Sexe in the schema.
        /// </summary>
        [Column(Name = @"sexe", Storage = "_Sexe", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Sexe
        {
            get
            {
                return this._Sexe;
            }
            set
            {
                if (this._Sexe != value)
                {
                    this.OnSexeChanging(value);
                    this.SendPropertyChanging("Sexe");
                    this._Sexe = value;
                    this.SendPropertyChanged("Sexe");
                    this.OnSexeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Photo in the schema.
        /// </summary>
        [Column(Name = @"photo", Storage = "_Photo", DbType = "LONGBLOB NULL", UpdateCheck = UpdateCheck.Never)]
        public byte[] Photo
        {
            get
            {
                return this._Photo;
            }
            set
            {
                if (this._Photo != value)
                {
                    this.OnPhotoChanging(value);
                    this.SendPropertyChanging("Photo");
                    this._Photo = value;
                    this.SendPropertyChanged("Photo");
                    this.OnPhotoChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Tournoi in the schema.
        /// </summary>
        [Column(Name = @"tournoi", Storage = "_Tournoi", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int Tournoi
        {
            get
            {
                return this._Tournoi;
            }
            set
            {
                if (this._Tournoi != value)
                {
                    if (this._Tournoi1.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnTournoiChanging(value);
                    this.SendPropertyChanging("Tournoi");
                    this._Tournoi = value;
                    this.SendPropertyChanged("Tournoi");
                    this.OnTournoiChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Tournoi1 in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Tournoi_Participant", Storage="_Tournoi1", ThisKey="Tournoi", OtherKey="IdTournoi", IsForeignKey=true)]
        public Tournoi Tournoi1
        {
            get
            {
                return this._Tournoi1.Entity;
            }
            set
            {
                Tournoi previousValue = this._Tournoi1.Entity;
                if ((previousValue != value) || (this._Tournoi1.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Tournoi1");
                    if (previousValue != null)
                    {
                        this._Tournoi1.Entity = null;
                        previousValue.Participants.Remove(this);
                    }
                    this._Tournoi1.Entity = value;
                    if (value != null)
                    {
                        this._Tournoi = value.IdTournoi;
                        value.Participants.Add(this);
                    }
                    else
                    {
                        this._Tournoi = default(int);
                    }
                    this.SendPropertyChanged("Tournoi1");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for BddtournoiContext.Sport in the schema.
    /// </summary>
    [Table(Name = @"bddtournois.sport")]
    public partial class Sport : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _IdSport;

        private string _Intitule;
        #pragma warning restore 0649

        private EntitySet<Tournoi> _Tournois;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdSportChanging(int value);
        partial void OnIdSportChanged();
        partial void OnIntituleChanging(string value);
        partial void OnIntituleChanged();
        #endregion

        public Sport()
        {
            this._Tournois = new EntitySet<Tournoi>(new Action<Tournoi>(this.attach_Tournois), new Action<Tournoi>(this.detach_Tournois));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdSport in the schema.
        /// </summary>
        [Column(Name = @"idSport", Storage = "_IdSport", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int IdSport
        {
            get
            {
                return this._IdSport;
            }
            set
            {
                if (this._IdSport != value)
                {
                    this.OnIdSportChanging(value);
                    this.SendPropertyChanging("IdSport");
                    this._IdSport = value;
                    this.SendPropertyChanged("IdSport");
                    this.OnIdSportChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Intitule in the schema.
        /// </summary>
        [Column(Name = @"intitule", Storage = "_Intitule", CanBeNull = false, DbType = "TEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Intitule
        {
            get
            {
                return this._Intitule;
            }
            set
            {
                if (this._Intitule != value)
                {
                    this.OnIntituleChanging(value);
                    this.SendPropertyChanging("Intitule");
                    this._Intitule = value;
                    this.SendPropertyChanged("Intitule");
                    this.OnIntituleChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Tournois in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Sport_Tournoi", Storage="_Tournois", ThisKey="IdSport", OtherKey="Sport", DeleteRule="RESTRICT")]
        public EntitySet<Tournoi> Tournois
        {
            get
            {
                return this._Tournois;
            }
            set
            {
                this._Tournois.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Tournois(Tournoi entity)
        {
            this.SendPropertyChanging("Tournois");
            entity.Sport1 = this;
        }
    
        private void detach_Tournois(Tournoi entity)
        {
            this.SendPropertyChanging("Tournois");
            entity.Sport1 = null;
        }
    }

    /// <summary>
    /// There are no comments for BddtournoiContext.Tournoi in the schema.
    /// </summary>
    [Table(Name = @"bddtournois.tournoi")]
    public partial class Tournoi : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _IdTournoi;

        private string _Intitule;

        private System.DateTime _DateTournoi;

        private int _Sport;
        #pragma warning restore 0649

        private EntitySet<Participant> _Participants;

        private EntityRef<Sport> _Sport1;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdTournoiChanging(int value);
        partial void OnIdTournoiChanged();
        partial void OnIntituleChanging(string value);
        partial void OnIntituleChanged();
        partial void OnDateTournoiChanging(System.DateTime value);
        partial void OnDateTournoiChanged();
        partial void OnSportChanging(int value);
        partial void OnSportChanged();
        #endregion

        public Tournoi()
        {
            this._Participants = new EntitySet<Participant>(new Action<Participant>(this.attach_Participants), new Action<Participant>(this.detach_Participants));
            this._Sport1  = default(EntityRef<Sport>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for IdTournoi in the schema.
        /// </summary>
        [Column(Name = @"idTournoi", Storage = "_IdTournoi", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int IdTournoi
        {
            get
            {
                return this._IdTournoi;
            }
            set
            {
                if (this._IdTournoi != value)
                {
                    this.OnIdTournoiChanging(value);
                    this.SendPropertyChanging("IdTournoi");
                    this._IdTournoi = value;
                    this.SendPropertyChanged("IdTournoi");
                    this.OnIdTournoiChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Intitule in the schema.
        /// </summary>
        [Column(Name = @"intitule", Storage = "_Intitule", CanBeNull = false, DbType = "TEXT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Intitule
        {
            get
            {
                return this._Intitule;
            }
            set
            {
                if (this._Intitule != value)
                {
                    this.OnIntituleChanging(value);
                    this.SendPropertyChanging("Intitule");
                    this._Intitule = value;
                    this.SendPropertyChanged("Intitule");
                    this.OnIntituleChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DateTournoi in the schema.
        /// </summary>
        [Column(Name = @"dateTournoi", Storage = "_DateTournoi", CanBeNull = false, DbType = "DATE NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime DateTournoi
        {
            get
            {
                return this._DateTournoi;
            }
            set
            {
                if (this._DateTournoi != value)
                {
                    this.OnDateTournoiChanging(value);
                    this.SendPropertyChanging("DateTournoi");
                    this._DateTournoi = value;
                    this.SendPropertyChanged("DateTournoi");
                    this.OnDateTournoiChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Sport in the schema.
        /// </summary>
        [Column(Storage = "_Sport", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int Sport
        {
            get
            {
                return this._Sport;
            }
            set
            {
                if (this._Sport != value)
                {
                    if (this._Sport1.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnSportChanging(value);
                    this.SendPropertyChanging("Sport");
                    this._Sport = value;
                    this.SendPropertyChanged("Sport");
                    this.OnSportChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Participants in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Tournoi_Participant", Storage="_Participants", ThisKey="IdTournoi", OtherKey="Tournoi", DeleteRule="RESTRICT")]
        public EntitySet<Participant> Participants
        {
            get
            {
                return this._Participants;
            }
            set
            {
                this._Participants.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Sport1 in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Sport_Tournoi", Storage="_Sport1", ThisKey="Sport", OtherKey="IdSport", IsForeignKey=true)]
        public Sport Sport1
        {
            get
            {
                return this._Sport1.Entity;
            }
            set
            {
                Sport previousValue = this._Sport1.Entity;
                if ((previousValue != value) || (this._Sport1.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Sport1");
                    if (previousValue != null)
                    {
                        this._Sport1.Entity = null;
                        previousValue.Tournois.Remove(this);
                    }
                    this._Sport1.Entity = value;
                    if (value != null)
                    {
                        this._Sport = value.IdSport;
                        value.Tournois.Add(this);
                    }
                    else
                    {
                        this._Sport = default(int);
                    }
                    this.SendPropertyChanged("Sport1");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Participants(Participant entity)
        {
            this.SendPropertyChanging("Participants");
            entity.Tournoi1 = this;
        }
    
        private void detach_Participants(Participant entity)
        {
            this.SendPropertyChanging("Participants");
            entity.Tournoi1 = null;
        }
    }

}
